
default: &default
  adapter: postgresql
  encoding: unicode


development:
  <<: *default
  database: local-business_development


test:
  <<: *default
  database: local-business_test


production:
  <<: *default
  database: local-business_production
  username: local-business
  password: <%= ENV['LOCAL-BUSINESS_DATABASE_PASSWORD'] %>
